version: "3.7"

services:

  v2ray:
    image: v2ray/official
    container_name: v2ray
    volumes:
      - ./config.json:/etc/v2ray/config.json
    expose:
      - "81"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - v2ray