FROM python:3.7

RUN pip install shadowsocks \
    && sed -i "s/EVP_CIPHER_CTX_cleanup/EVP_CIPHER_CTX_reset/" /usr/local/lib/python3.7/site-packages/shadowsocks/crypto/openssl.py \
    && git clone -b stable https://github.com/alexbers/mtprotoproxy.git

COPY start.sh /start.sh

ENTRYPOINT ["sh", "start.sh"]